### ISSUE TITLE
No ShortCode in product.description and the content does not show

### ISSUE THREAD

**Issue by sturple** [Carted/shopify-shortcodes#4]
Thank you for your shortcode snippets, however i found a little glitch, if there is something that im doing wrong maybe you can help out, otherwise this is what i found.

In my product.liquid I added the following code  {% include 'shortcode' load: product.description  %}   in place of {{product.description}}   If i put a shortcode in a product it displays the product.description, if no shortcode is present then it doesn't show any content.
This fails because of this statement {% if shortcodeBegins.size > 1 %} in shortcode.liquid,

 if you put an {% else %}{{loadnew}}{%endif%}} in the shortcode.liquid  it fixed loading the product description that didn't have a shortcode

Thanks

**Comment by evulse** [comment]
Hey @sturple thanks for pointing this out, I have just pushed an update to resolve this.
